language: python
python:
  - 3.6
  - 3.7
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install .
script: pytest -v 
after_success:
  - codecov 
